site_name: 索引狗的博客
site_url: https://indexdog.github.io/mymkdocs
site_author: index_dog

use_directory_urls: false  # 修复404跳转问题

theme:
  name: material
  custom_dir: docs/overrides

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  favicon: 'favicon.ico'
  icon:
    logo: 'material/school'

  features: 
    - announce.dismiss
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.expand
    #- navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate

  language: zh

copyright: 'Copyright &copy; 2024-2024 indexdog'

plugins:
  - search

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - markdown.extensions.toc:
      permalink: "\ue157"

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 学习:
      - 语言基础:
          - C: STUDY/language/c.md
          - C#: STUDY/language/c_sharp.md
          - Python: STUDY/language/py.md
      - 常用指令:
          - Markdown语法: STUDY/instruct/md.md
      - Python相关:
          - Jupyter Notebook 快捷键: STUDY/instruct/jn.md
          - Matplotlib 用法: STUDY/py/matplotlib.md
          - Numpy & Pandas 用法: STUDY/py/numpypandas.md
      - 算法学习:
          - 算法基础: STUDY/algorithm/note.md
          - 蓝桥杯备赛: STUDY/algorithm/lanqiao.md
          - STL 总结: STUDY/algorithm/stl.md
          - 算法精选: STUDY/algorithm/junior.md
      - 数据结构:
          - 数据结构基础（转载）: STUDY/datastru/bj.md
      - 并行计算:
          - MPI 编程: STUDY/bxjs/MPI.md
      - Docker:
          - Docker 简介: STUDY/docker/docker_intro.md
          - WSL 部署 Docker: STUDY/docker/docker_wsl.md
          - Docker 命令: STUDY/docker/docker_instruct.md
          - Dockerfile: STUDY/docker/dockerfile0.md
      - Tools in Coding:
          - Vim: STUDY/tools/vim.md
      - MkDocs 遇到的问题: STUDY/mkdocsq/q.md

  - Project:
      - 大模型微调: PROJECT/llm/llm.md

  - 课程资料:
      - 形式化方法:
          - 课程介绍: COURSE/FM/fm.md
          - Introduction of Formal Methods: COURSE/FM/fm1.md
          - Set Theory: COURSE/FM/fm2.md
          - Types in Z: COURSE/FM/3.md
          - Schema: COURSE/FM/4.md
          - Predicates and Quantifiers in Z: COURSE/FM/5.md
          - Functions in Z: COURSE/FM/6.md
          - Sequences in Z: COURSE/FM/7.md
          - Bags in Z: COURSE/FM/8.md
          - Hints on Creating Specification: COURSE/FM/9.md

  - Idea:
      - 实用工具分享: 
          - 网站: BLOG/website.md
      - 碎碎念: 
          - 学习记录: BLOG/chat.md
